language: python
python:
  - "2.7"
  - "2.6"
install:
  # Build/test dependencies
  - pip install -r requirements.txt
script:
- python -m compileall library/*.py
- python -m compileall plugins/lookup/*.py
- python -m compileall plugins/filter/*.py
- nosetests
notifications:
  slack: virtualcomputing:sE3KduFaTBjq0jGEwPdxs0Qr
